<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AirlineSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $airlines = [
            ['name' => 'American Airlines', 'iata' => 'AA', 'icao' => 'AAL'],
            ['name' => 'Delta Air Lines', 'iata' => 'DL', 'icao' => 'DAL'],
            ['name' => 'United Airlines', 'iata' => 'UA', 'icao' => 'UAL'],
            ['name' => 'Southwest Airlines', 'iata' => 'WN', 'icao' => 'SWA'],
            ['name' => 'Lufthansa', 'iata' => 'LH', 'icao' => 'DLH'],
            ['name' => 'Emirates', 'iata' => 'EK', 'icao' => 'UAE'],
            ['name' => 'Qatar Airways', 'iata' => 'QR', 'icao' => 'QTR'],
            ['name' => 'British Airways', 'iata' => 'BA', 'icao' => 'BAW'],
            ['name' => 'Air France', 'iata' => 'AF', 'icao' => 'AFR'],
            ['name' => 'Singapore Airlines', 'iata' => 'SQ', 'icao' => 'SIA'],
            ['name' => 'Cathay Pacific', 'iata' => 'CX', 'icao' => 'CPA'],
            ['name' => 'Turkish Airlines', 'iata' => 'TK', 'icao' => 'THY'],
            ['name' => 'Etihad Airways', 'iata' => 'EY', 'icao' => 'ETD'],
            ['name' => 'Japan Airlines', 'iata' => 'JL', 'icao' => 'JAL'],
            ['name' => 'KLM Royal Dutch Airlines', 'iata' => 'KL', 'icao' => 'KLM'],
            ['name' => 'Qantas', 'iata' => 'QF', 'icao' => 'QFA'],
            ['name' => 'All Nippon Airways', 'iata' => 'NH', 'icao' => 'ANA'],
            ['name' => 'Swiss International Air Lines', 'iata' => 'LX', 'icao' => 'SWR'],
            ['name' => 'Thai Airways', 'iata' => 'TG', 'icao' => 'THA'],
            ['name' => 'Air Canada', 'iata' => 'AC', 'icao' => 'ACA'],
            ['name' => 'Alitalia', 'iata' => 'AZ', 'icao' => 'AZA'],
            ['name' => 'Aeroflot', 'iata' => 'SU', 'icao' => 'AFL'],
            ['name' => 'Avianca', 'iata' => 'AV', 'icao' => 'AVA'],
            ['name' => 'Iberia', 'iata' => 'IB', 'icao' => 'IBE'],
            ['name' => 'Finnair', 'iata' => 'AY', 'icao' => 'FIN'],
            ['name' => 'Air India', 'iata' => 'AI', 'icao' => 'AIC'],
            ['name' => 'South African Airways', 'iata' => 'SA', 'icao' => 'SAA'],
            ['name' => 'Korean Air', 'iata' => 'KE', 'icao' => 'KAL'],
            ['name' => 'Asiana Airlines', 'iata' => 'OZ', 'icao' => 'AAR'],
            ['name' => 'Scandinavian Airlines', 'iata' => 'SK', 'icao' => 'SAS'],
            ['name' => 'Malaysia Airlines', 'iata' => 'MH', 'icao' => 'MAS'],
            ['name' => 'China Airlines', 'iata' => 'CI', 'icao' => 'CAL'],
            ['name' => 'Austrian Airlines', 'iata' => 'OS', 'icao' => 'AUA'],
            ['name' => 'Philippine Airlines', 'iata' => 'PR', 'icao' => 'PAL'],
            ['name' => 'Garuda Indonesia', 'iata' => 'GA', 'icao' => 'GIA'],
            ['name' => 'Kenya Airways', 'iata' => 'KQ', 'icao' => 'KQA'],
            ['name' => 'Saudia', 'iata' => 'SV', 'icao' => 'SVA'],
            ['name' => 'Royal Air Maroc', 'iata' => 'AT', 'icao' => 'RAM'],
            ['name' => 'Vietnam Airlines', 'iata' => 'VN', 'icao' => 'HVN'],
            ['name' => 'Royal Jordanian', 'iata' => 'RJ', 'icao' => 'RJA'],
            ['name' => 'SriLankan Airlines', 'iata' => 'UL', 'icao' => 'ALK'],
            ['name' => 'TAP Air Portugal', 'iata' => 'TP', 'icao' => 'TAP'],
            ['name' => 'Aeroméxico', 'iata' => 'AM', 'icao' => 'AMX'],
            ['name' => 'EgyptAir', 'iata' => 'MS', 'icao' => 'MSR'],
            ['name' => 'Gulf Air', 'iata' => 'GF', 'icao' => 'GFA'],
            ['name' => 'Pakistan International Airlines', 'iata' => 'PK', 'icao' => 'PIA'],
            ['name' => 'LATAM Airlines', 'iata' => 'LA', 'icao' => 'LAN'],
            ['name' => 'El Al', 'iata' => 'LY', 'icao' => 'ELY'],
            ['name' => 'Brussels Airlines', 'iata' => 'SN', 'icao' => 'BEL'],
            ['name' => 'Virgin Atlantic', 'iata' => 'VS', 'icao' => 'VIR'],
            ['name' => 'EasyJet', 'iata' => 'U2', 'icao' => 'EZY'],
            ['name' => 'Ryanair', 'iata' => 'FR', 'icao' => 'RYR'],
            ['name' => 'Wizz Air', 'iata' => 'W6', 'icao' => 'WZZ'],
            ['name' => 'JetBlue Airways', 'iata' => 'B6', 'icao' => 'JBU'],
            ['name' => 'Spirit Airlines', 'iata' => 'NK', 'icao' => 'NKS'],
            ['name' => 'Frontier Airlines', 'iata' => 'F9', 'icao' => 'FFT'],
            ['name' => 'Alaska Airlines', 'iata' => 'AS', 'icao' => 'ASA'],
            ['name' => 'Hawaiian Airlines', 'iata' => 'HA', 'icao' => 'HAL'],
            ['name' => 'WestJet', 'iata' => 'WS', 'icao' => 'WJA'],
            ['name' => 'Allegiant Air', 'iata' => 'G4', 'icao' => 'AAY'],
            ['name' => 'Vueling', 'iata' => 'VY', 'icao' => 'VLG'],
            ['name' => 'AirAsia', 'iata' => 'AK', 'icao' => 'AXM'],
            ['name' => 'Scoot', 'iata' => 'TR', 'icao' => 'TGW'],
            ['name' => 'Jetstar Airways', 'iata' => 'JQ', 'icao' => 'JST'],
            ['name' => 'Air New Zealand', 'iata' => 'NZ', 'icao' => 'ANZ'],
            ['name' => 'Air Transat', 'iata' => 'TS', 'icao' => 'TSC'],
            ['name' => 'Cebu Pacific', 'iata' => '5J', 'icao' => 'CEB'],
            ['name' => 'IndiGo', 'iata' => '6E', 'icao' => 'IGO'],
            ['name' => 'SpiceJet', 'iata' => 'SG', 'icao' => 'SEJ'],
            ['name' => 'GoAir', 'iata' => 'G8', 'icao' => 'GOW'],
            ['name' => 'AirAsia X', 'iata' => 'D7', 'icao' => 'XAX'],
            ['name' => 'Norwegian Air Shuttle', 'iata' => 'DY', 'icao' => 'NAX'],
            ['name' => 'Tigerair', 'iata' => 'TR', 'icao' => 'TGW'],
            ['name' => 'VivaAerobus', 'iata' => 'VB', 'icao' => 'VIV'],
            ['name' => 'Azul Brazilian Airlines', 'iata' => 'AD', 'icao' => 'AZU'],
            ['name' => 'Gol Transportes Aéreos', 'iata' => 'G3', 'icao' => 'GLO'],
            ['name' => 'Sky Airline', 'iata' => 'H2', 'icao' => 'SKU'],
            ['name' => 'LATAM Brasil', 'iata' => 'JJ', 'icao' => 'TAM'],
            ['name' => 'Copa Airlines', 'iata' => 'CM', 'icao' => 'CMP'],
            ['name' => 'Air Europa', 'iata' => 'UX', 'icao' => 'AEA'],
            ['name' => 'Norwegian Air International', 'iata' => 'D8', 'icao' => 'IBK'],
            ['name' => 'Air Arabia', 'iata' => 'G9', 'icao' => 'ABY'],
            ['name' => 'flydubai', 'iata' => 'FZ', 'icao' => 'FDB'],
            ['name' => 'Oman Air', 'iata' => 'WY', 'icao' => 'OMA'],
            ['name' => 'Biman Bangladesh Airlines', 'iata' => 'BG', 'icao' => 'BBC'],
            ['name' => 'Royal Brunei Airlines', 'iata' => 'BI', 'icao' => 'RBA'],
            ['name' => 'Bangkok Airways', 'iata' => 'PG', 'icao' => 'BKP'],
            ['name' => 'Lion Air', 'iata' => 'JT', 'icao' => 'LNI'],
            ['name' => 'SilkAir', 'iata' => 'MI', 'icao' => 'SLK'],
            ['name' => 'TUI Airways', 'iata' => 'BY', 'icao' => 'TOM'],
            ['name' => 'Jet2.com', 'iata' => 'LS', 'icao' => 'EXS'],
            ['name' => 'Monarch Airlines', 'iata' => 'ZB', 'icao' => 'MON'],
            ['name' => 'Air Serbia', 'iata' => 'JU', 'icao' => 'ASL'],
            ['name' => 'Widerøe', 'iata' => 'WF', 'icao' => 'WIF'],
            ['name' => 'S7 Airlines', 'iata' => 'S7', 'icao' => 'SBI'],
            ['name' => 'Ural Airlines', 'iata' => 'U6', 'icao' => 'SVR'],
            ['name' => 'Aer Lingus', 'iata' => 'EI', 'icao' => 'EIN'],
            ['name' => 'LOT Polish Airlines', 'iata' => 'LO', 'icao' => 'LOT'],
            ['name' => 'Aegean Airlines', 'iata' => 'A3', 'icao' => 'AEE'],
            ['name' => 'Czech Airlines', 'iata' => 'OK', 'icao' => 'CSA'],
            ['name' => 'Air Malta', 'iata' => 'KM', 'icao' => 'AMC'],
            ['name' => 'Icelandair', 'iata' => 'FI', 'icao' => 'ICE'],
            ['name' => 'Norwegian Air Argentina', 'iata' => 'DN', 'icao' => 'NAA'],
            ['name' => 'Norwegian Air UK', 'iata' => 'DI', 'icao' => 'NRS'],
            ['name' => 'LEVEL', 'iata' => 'IB', 'icao' => 'LVL'],
            ['name' => 'West Atlantic UK', 'iata' => 'NPT', 'icao' => 'NPT'],
            ['name' => 'Royal Air Force', 'iata' => 'RR', 'icao' => 'RFR'],
            ['name' => 'Austrian Air Force', 'iata' => 'OE', 'icao' => 'AUS'],
            ['name' => 'Edelweiss Air', 'iata' => 'WK', 'icao' => 'EDW'],
            ['name' => 'La Compagnie', 'iata' => 'B0', 'icao' => 'DJT'],
            ['name' => 'TAROM', 'iata' => 'RO', 'icao' => 'ROT'],
            ['name' => 'Air Greenland', 'iata' => 'GL', 'icao' => 'GRL'],
            ['name' => 'Blue Air', 'iata' => '0B', 'icao' => 'BMS'],
            ['name' => 'Moldavian Airlines', 'iata' => '2M', 'icao' => 'MDV'],
            ['name' => 'Air Moldova', 'iata' => '9U', 'icao' => 'MLD'],
            ['name' => 'Belavia', 'iata' => 'B2', 'icao' => 'BRU'],
            ['name' => 'LOT Charters', 'iata' => 'LLC', 'icao' => 'LLC'],
            ['name' => 'Windrose Airlines', 'iata' => '7W', 'icao' => 'WRC'],
            ['name' => 'Dniproavia', 'iata' => 'Z6', 'icao' => 'UDN'],
            ['name' => 'Donbassaero', 'iata' => '7D', 'icao' => 'UDC'],
            ['name' => 'Ukraine International Airlines', 'iata' => 'PS', 'icao' => 'AUI'],
            ['name' => 'Turkmenistan Airlines', 'iata' => 'T5', 'icao' => 'TUA'],
            ['name' => 'Uzbekistan Airways', 'iata' => 'HY', 'icao' => 'UZB'],
            ['name' => 'Somon Air', 'iata' => 'SZ', 'icao' => 'SMR'],
            ['name' => 'Air Astana', 'iata' => 'KC', 'icao' => 'KZR'],
            ['name' => 'Scat Airlines', 'iata' => 'DV', 'icao' => 'VSV'],
            ['name' => 'Air Manas', 'iata' => 'ZM', 'icao' => 'MBB'],
            ['name' => 'Air Bishkek', 'iata' => 'KR', 'icao' => 'EAA'],
            ['name' => 'Tajik Air', 'iata' => '7J', 'icao' => 'TJK'],
            ['name' => 'Mahan Air', 'iata' => 'W5', 'icao' => 'IRM'],
            ['name' => 'Iran Air', 'iata' => 'IR', 'icao' => 'IRA'],
            ['name' => 'Kuwait Airways', 'iata' => 'KU', 'icao' => 'KAC'],
            ['name' => 'Iran Aseman Airlines', 'iata' => 'EP', 'icao' => 'IRC'],
            ['name' => 'Air China', 'iata' => 'CA', 'icao' => 'CCA'],
            ['name' => 'China Southern Airlines', 'iata' => 'CZ', 'icao' => 'CSN'],
            ['name' => 'China Eastern Airlines', 'iata' => 'MU', 'icao' => 'CES'],
            ['name' => 'XiamenAir', 'iata' => 'MF', 'icao' => 'CXA'],
            ['name' => 'Hainan Airlines', 'iata' => 'HU', 'icao' => 'CHH'],
            ['name' => 'Shenzhen Airlines', 'iata' => 'ZH', 'icao' => 'CSZ'],
            ['name' => 'Sichuan Airlines', 'iata' => '3U', 'icao' => 'CSC'],
            ['name' => 'Air Macau', 'iata' => 'NX', 'icao' => 'AMU'],
            ['name' => 'Hong Kong Airlines', 'iata' => 'HX', 'icao' => 'CRK'],
            ['name' => 'Hong Kong Express Airways', 'iata' => 'UO', 'icao' => 'HKE'],
            ['name' => 'Mandarin Airlines', 'iata' => 'AE', 'icao' => 'MDA'],
            ['name' => 'Uni Air', 'iata' => 'B7', 'icao' => 'UIA'],
            ['name' => 'EVA Air', 'iata' => 'BR', 'icao' => 'EVA'],
            ['name' => 'TransAsia Airways', 'iata' => 'GE', 'icao' => 'TNA'],
            ['name' => 'Juneyao Airlines', 'iata' => 'HO', 'icao' => 'DKH'],
            ['name' => 'Shandong Airlines', 'iata' => 'SC', 'icao' => 'CDG'],
            ['name' => 'China United Airlines', 'iata' => 'KN', 'icao' => 'CUA'],
            ['name' => 'Hebei Airlines', 'iata' => 'NS', 'icao' => 'HBH'],
            ['name' => 'Tibet Airlines', 'iata' => 'TV', 'icao' => 'TBA'],
            ['name' => 'China Express Airlines', 'iata' => 'G5', 'icao' => 'HXA'],
            ['name' => 'Lucky Air', 'iata' => '8L', 'icao' => 'LKE'],
            ['name' => 'Qingdao Airlines', 'iata' => 'QW', 'icao' => 'QDA'],
            ['name' => 'GX Airlines', 'iata' => 'GX', 'icao' => 'CBG'],
            ['name' => 'Ruili Airlines', 'iata' => 'DR', 'icao' => 'RLH'],
            ['name' => 'Sichuan Airlines', 'iata' => '3U', 'icao' => 'CSC'],
            ['name' => 'Loong Air', 'iata' => 'GJ', 'icao' => 'CDC'],
            ['name' => 'Fuzhou Airlines', 'iata' => 'FU', 'icao' => 'FZA'],
            ['name' => 'Okay Airways', 'iata' => 'BK', 'icao' => 'OKA'],
            ['name' => 'Shanghai Airlines', 'iata' => 'FM', 'icao' => 'CSH'],
            ['name' => 'Spring Airlines', 'iata' => '9C', 'icao' => 'CQH'],
            ['name' => 'AirAsia X', 'iata' => 'D7', 'icao' => 'XAX'],
            ['name' => 'Scoot', 'iata' => 'TR', 'icao' => 'TGW'],
            ['name' => 'Jetstar Asia Airways', 'iata' => '3K', 'icao' => 'JSA'],
            ['name' => 'Tigerair Taiwan', 'iata' => 'IT', 'icao' => 'TTW'],
            ['name' => 'Cebu Pacific', 'iata' => '5J', 'icao' => 'CEB'],
            ['name' => 'Philippines AirAsia', 'iata' => 'Z2', 'icao' => 'APG'],
            ['name' => 'PAL Express', 'iata' => '2P', 'icao' => 'GAP'],
            ['name' => 'Royal Air Charter Service', 'iata' => 'RW', 'icao' => 'RYS'],
            ['name' => 'Saudia', 'iata' => 'SV', 'icao' => 'SVA'],
            ['name' => 'Flynas', 'iata' => 'XY', 'icao' => 'KNE'],
            ['name' => 'flyadeal', 'iata' => 'F3', 'icao' => 'FAD'],
            ['name' => 'Air India', 'iata' => 'AI', 'icao' => 'AIC'],
            ['name' => 'Vistara', 'iata' => 'UK', 'icao' => 'VTI'],
            ['name' => 'IndiGo', 'iata' => '6E', 'icao' => 'IGO'],
            ['name' => 'AirAsia India', 'iata' => 'I5', 'icao' => 'IAD'],
            ['name' => 'SpiceJet', 'iata' => 'SG', 'icao' => 'SEJ'],
            ['name' => 'GoAir', 'iata' => 'G8', 'icao' => 'GOW'],
            ['name' => 'Akasa Air', 'iata' => 'QP', 'icao' => 'AKJ'],
            ['name' => 'Alliance Air', 'iata' => '9I', 'icao' => 'LLR'],
            ['name' => 'TruJet', 'iata' => '2T', 'icao' => 'TRJ'],
            ['name' => 'Flybig', 'iata' => 'S9', 'icao' => 'FLG'],
            ['name' => 'Zoom Air', 'iata' => 'Z9', 'icao' => 'OOM'],
            ['name' => 'Helitrans', 'iata' => '9E', 'icao' => 'HTN'],
            ['name' => 'Skylink Aviation', 'iata' => 'SLQ', 'icao' => 'SLQ'],
            ['name' => 'Orbest', 'iata' => '6O', 'icao' => 'OBS'],
            ['name' => 'Aigle Azur', 'iata' => 'ZI', 'icao' => 'AAF'],
            ['name' => 'Oman Air', 'iata' => 'WY', 'icao' => 'OMA'],
            ['name' => 'Qatar Airways', 'iata' => 'QR', 'icao' => 'QTR'],
            ['name' => 'Singapore Airlines', 'iata' => 'SQ', 'icao' => 'SIA'],
            ['name' => 'Thai Airways', 'iata' => 'TG', 'icao' => 'THA'],
            ['name' => 'Vietnam Airlines', 'iata' => 'VN', 'icao' => 'HVN'],
            ['name' => 'Garuda Indonesia', 'iata' => 'GA', 'icao' => 'GIA'],
            ['name' => 'Malaysia Airlines', 'iata' => 'MH', 'icao' => 'MAS'],
            ['name' => 'Philippine Airlines', 'iata' => 'PR', 'icao' => 'PAL'],
            ['name' => 'Royal Brunei Airlines', 'iata' => 'BI', 'icao' => 'RBA'],
            ['name' => 'Turkish Airlines', 'iata' => 'TK', 'icao' => 'THY'],
            ['name' => 'KLM Royal Dutch Airlines', 'iata' => 'KL', 'icao' => 'KLM'],
            ['name' => 'Air France', 'iata' => 'AF', 'icao' => 'AFR'],
            ['name' => 'Lufthansa', 'iata' => 'LH', 'icao' => 'DLH'],
            ['name' => 'Swiss International Air Lines', 'iata' => 'LX', 'icao' => 'SWR'],
            ['name' => 'Austrian Airlines', 'iata' => 'OS', 'icao' => 'AUA'],
            ['name' => 'Scandinavian Airlines', 'iata' => 'SK', 'icao' => 'SAS'],
            ['name' => 'Finnair', 'iata' => 'AY', 'icao' => 'FIN'],
            ['name' => 'Icelandair', 'iata' => 'FI', 'icao' => 'ICE'],
            ['name' => 'Air Europa', 'iata' => 'UX', 'icao' => 'AEA'],
            ['name' => 'Iberia', 'iata' => 'IB', 'icao' => 'IBE'],
            ['name' => 'TAP Air Portugal', 'iata' => 'TP', 'icao' => 'TAP'],
            ['name' => 'British Airways', 'iata' => 'BA', 'icao' => 'BAW'],
            ['name' => 'Virgin Atlantic', 'iata' => 'VS', 'icao' => 'VIR'],
            ['name' => 'Ryanair', 'iata' => 'FR', 'icao' => 'RYR'],
            ['name' => 'easyJet', 'iata' => 'U2', 'icao' => 'EZY'],
            ['name' => 'Wizz Air', 'iata' => 'W6', 'icao' => 'WZZ'],
            ['name' => 'Norwegian', 'iata' => 'DY', 'icao' => 'NAX'],
            ['name' => 'Jet2.com', 'iata' => 'LS', 'icao' => 'EXS'],
            ['name' => 'TUI Airways', 'iata' => 'BY', 'icao' => 'TOM'],
            ['name' => 'Condor', 'iata' => 'DE', 'icao' => 'CFG'],
            ['name' => 'Eurowings', 'iata' => 'EW', 'icao' => 'EWG'],
            ['name' => 'Vueling Airlines', 'iata' => 'VY', 'icao' => 'VLG'],
            ['name' => 'Aer Lingus', 'iata' => 'EI', 'icao' => 'EIN'],
            ['name' => 'Air Malta', 'iata' => 'KM', 'icao' => 'AMC'],
            ['name' => 'Aegean Airlines', 'iata' => 'A3', 'icao' => 'AEE'],
            ['name' => 'Olympic Air', 'iata' => 'OA', 'icao' => 'OAL'],
            ['name' => 'Czech Airlines', 'iata' => 'OK', 'icao' => 'CSA'],
            ['name' => 'LOT Polish Airlines', 'iata' => 'LO', 'icao' => 'LOT'],
            ['name' => 'Air Serbia', 'iata' => 'JU', 'icao' => 'ASL'],
            ['name' => 'Croatia Airlines', 'iata' => 'OU', 'icao' => 'CTN'],
            ['name' => 'Montenegro Airlines', 'iata' => 'YM', 'icao' => 'MGX'],
            ['name' => 'TAROM', 'iata' => 'RO', 'icao' => 'ROT'],
            ['name' => 'Air Baltic', 'iata' => 'BT', 'icao' => 'BTI'],
            ['name' => 'Air Moldova', 'iata' => '9U', 'icao' => 'MLD'],
            ['name' => 'Ukraine International Airlines', 'iata' => 'PS', 'icao' => 'AUI'],
            ['name' => 'Belavia', 'iata' => 'B2', 'icao' => 'BRU'],
            ['name' => 'Utair', 'iata' => 'UT', 'icao' => 'UTA'],
            ['name' => 'Azimuth', 'iata' => 'A4', 'icao' => 'AZO'],
            ['name' => 'RusLine', 'iata' => '7R', 'icao' => 'RLU'],
            ['name' => 'FlyArystan', 'iata' => 'KC', 'icao' => 'KZR'],
            ['name' => 'Qazaq Air', 'iata' => 'IQ', 'icao' => 'QAZ'],
            ['name' => 'SCAT Airlines', 'iata' => 'DV', 'icao' => 'VSV'],
            ['name' => 'Air Astana', 'iata' => 'KC', 'icao' => 'KZR'],
            ['name' => 'Ural Airlines', 'iata' => 'U6', 'icao' => 'SVR'],
            ['name' => 'S7 Airlines', 'iata' => 'S7', 'icao' => 'SBI'],
            ['name' => 'Aeroflot', 'iata' => 'SU', 'icao' => 'AFL'],
            ['name' => 'Rossiya Airlines', 'iata' => 'FV', 'icao' => 'SDM'],
            ['name' => 'Pobeda', 'iata' => 'DP', 'icao' => 'PBD'],
            ['name' => 'Norwegian Air Shuttle', 'iata' => 'DY', 'icao' => 'NAX'],
            ['name' => 'Wizz Air UK', 'iata' => 'W9', 'icao' => 'WUK'],
            ['name' => 'Loganair', 'iata' => 'LM', 'icao' => 'LOG'],
            ['name' => 'Blue Islands', 'iata' => 'SI', 'icao' => 'BCI'],
            ['name' => 'Aurigny Air Services', 'iata' => 'GR', 'icao' => 'AUR'],
            ['name' => 'Ryanair UK', 'iata' => 'RK', 'icao' => 'RYR'],
            ['name' => 'Eastern Airways', 'iata' => 'T3', 'icao' => 'EZE'],
            ['name' => 'Air Mauritius', 'iata' => 'MK', 'icao' => 'MAU'],
            ['name' => 'Air Seychelles', 'iata' => 'HM', 'icao' => 'SEY'],
            ['name' => 'Air Austral', 'iata' => 'UU', 'icao' => 'REU'],
            ['name' => 'Ethiopian Airlines', 'iata' => 'ET', 'icao' => 'ETH'],
            ['name' => 'Kenya Airways', 'iata' => 'KQ', 'icao' => 'KQA'],
            ['name' => 'Air Tanzania', 'iata' => 'TC', 'icao' => 'ATC'],
            ['name' => 'Precision Air', 'iata' => 'PW', 'icao' => 'PRF'],
            ['name' => 'RwandAir', 'iata' => 'WB', 'icao' => 'RWD'],
            ['name' => 'South African Airways', 'iata' => 'SA', 'icao' => 'SAA'],
            ['name' => 'Air Namibia', 'iata' => 'SW', 'icao' => 'NMB'],
            ['name' => 'Lufthansa CityLine', 'iata' => 'CL', 'icao' => 'CLH'],
            ['name' => 'Eurowings Discover', 'iata' => '4Y', 'icao' => 'EWE'],
            ['name' => 'Azul Brazilian Airlines', 'iata' => 'AD', 'icao' => 'AZU'],
            ['name' => 'Gol Transportes Aéreos', 'iata' => 'G3', 'icao' => 'GLO'],
            ['name' => 'LATAM Airlines', 'iata' => 'LA', 'icao' => 'LAN'],
            ['name' => 'Avianca', 'iata' => 'AV', 'icao' => 'AVA'],
            ['name' => 'Copa Airlines', 'iata' => 'CM', 'icao' => 'CMP'],
            ['name' => 'Aeromexico', 'iata' => 'AM', 'icao' => 'AMX'],
            ['name' => 'Interjet', 'iata' => '4O', 'icao' => 'AIJ'],
            ['name' => 'Volaris', 'iata' => 'Y4', 'icao' => 'VOI'],
            ['name' => 'Viva Aerobus', 'iata' => 'VB', 'icao' => 'VIV'],
            ['name' => 'Tame', 'iata' => 'EQ', 'icao' => 'TAE'],
            ['name' => 'JetSmart', 'iata' => 'JA', 'icao' => 'JAT'],
            ['name' => 'Sky Airline', 'iata' => 'H2', 'icao' => 'SKU'],
            ['name' => 'Régional Compagnie Aérienne Européenne', 'iata' => 'YS', 'icao' => 'RAE'],
            ['name' => 'HOP!', 'iata' => 'A5', 'icao' => 'HOP'],
            ['name' => 'Air Corsica', 'iata' => 'XK', 'icao' => 'CCM'],
            ['name' => 'Transavia', 'iata' => 'HV', 'icao' => 'TRA'],
            ['name' => 'Corendon Airlines', 'iata' => 'XC', 'icao' => 'CAI'],
            ['name' => 'SunExpress', 'iata' => 'XQ', 'icao' => 'SXS'],
            ['name' => 'Air Algerie', 'iata' => 'AH', 'icao' => 'DAH'],
            ['name' => 'Royal Air Maroc', 'iata' => 'AT', 'icao' => 'RAM'],
            ['name' => 'Tunisair', 'iata' => 'TU', 'icao' => 'TAR'],
            ['name' => 'Air Arabia', 'iata' => 'G9', 'icao' => 'ABY'],
            ['name' => 'flydubai', 'iata' => 'FZ', 'icao' => 'FDB'],
            ['name' => 'Emirates', 'iata' => 'EK', 'icao' => 'UAE'],
            ['name' => 'Gulf Air', 'iata' => 'GF', 'icao' => 'GFA'],
            ['name' => 'Etihad Airways', 'iata' => 'EY', 'icao' => 'ETD'],
            ['name' => 'Qatar Airways', 'iata' => 'QR', 'icao' => 'QTR'],
            ['name' => 'Oman Air', 'iata' => 'WY', 'icao' => 'OMA'],
            ['name' => 'Kuwait Airways', 'iata' => 'KU', 'icao' => 'KAC'],
            ['name' => 'Air India Express', 'iata' => 'IX', 'icao' => 'AXB'],
            ['name' => 'SpiceJet', 'iata' => 'SG', 'icao' => 'SEJ'],
            ['name' => 'IndiGo', 'iata' => '6E', 'icao' => 'IGO'],
            ['name' => 'AirAsia India', 'iata' => 'I5', 'icao' => 'IAD'],
            ['name' => 'GoAir', 'iata' => 'G8', 'icao' => 'GOW'],
            ['name' => 'Vistara', 'iata' => 'UK', 'icao' => 'VTI'],
            ['name' => 'Akasa Air', 'iata' => 'QP', 'icao' => 'AKJ'],
            ['name' => 'Alliance Air', 'iata' => '9I', 'icao' => 'LLR'],
            ['name' => 'TruJet', 'iata' => '2T', 'icao' => 'TRJ'],
            ['name' => 'Flybig', 'iata' => 'S9', 'icao' => 'FLG'],
            ['name' => 'Zoom Air', 'iata' => 'Z9', 'icao' => 'OOM'],
            ['name' => 'Helitrans', 'iata' => '9E', 'icao' => 'HTN'],
            ['name' => 'Skylink Aviation', 'iata' => 'SLQ', 'icao' => 'SLQ'],
            ['name' => 'Orbest', 'iata' => '6O', 'icao' => 'OBS'],
            ['name' => 'Aigle Azur', 'iata' => 'ZI', 'icao' => 'AAF'],
            ['name' => 'Oman Air', 'iata' => 'WY', 'icao' => 'OMA'],
            ['name' => 'Qatar Airways', 'iata' => 'QR', 'icao' => 'QTR'],
            ['name' => 'Singapore Airlines', 'iata' => 'SQ', 'icao' => 'SIA'],
            ['name' => 'Thai Airways', 'iata' => 'TG', 'icao' => 'THA'],
            ['name' => 'Vietnam Airlines', 'iata' => 'VN', 'icao' => 'HVN'],
            ['name' => 'Garuda Indonesia', 'iata' => 'GA', 'icao' => 'GIA'],
            ['name' => 'Malaysia Airlines', 'iata' => 'MH', 'icao' => 'MAS'],
            ['name' => 'Philippine Airlines', 'iata' => 'PR', 'icao' => 'PAL'],
            ['name' => 'Royal Brunei Airlines', 'iata' => 'BI', 'icao' => 'RBA'],
            ['name' => 'Turkish Airlines', 'iata' => 'TK', 'icao' => 'THY'],
            ['name' => 'KLM Royal Dutch Airlines', 'iata' => 'KL', 'icao' => 'KLM'],
            ['name' => 'Air France', 'iata' => 'AF', 'icao' => 'AFR'],
            ['name' => 'Lufthansa', 'iata' => 'LH', 'icao' => 'DLH'],
            ['name' => 'Swiss International Air Lines', 'iata' => 'LX', 'icao' => 'SWR'],
            ['name' => 'Austrian Airlines', 'iata' => 'OS', 'icao' => 'AUA'],
            ['name' => 'Scandinavian Airlines', 'iata' => 'SK', 'icao' => 'SAS'],
            ['name' => 'Finnair', 'iata' => 'AY', 'icao' => 'FIN'],
            ['name' => 'Icelandair', 'iata' => 'FI', 'icao' => 'ICE'],
            ['name' => 'Aer Lingus', 'iata' => 'EI', 'icao' => 'EIN'],
            ['name' => 'TAP Air Portugal', 'iata' => 'TP', 'icao' => 'TAP'],
            ['name' => 'Luxair', 'iata' => 'LG', 'icao' => 'LGL'],
            ['name' => 'Alitalia', 'iata' => 'AZ', 'icao' => 'AZA'],
            ['name' => 'Iberia', 'iata' => 'IB', 'icao' => 'IBE'],
            ['name' => 'British Airways', 'iata' => 'BA', 'icao' => 'BAW'],
            ['name' => 'Virgin Atlantic', 'iata' => 'VS', 'icao' => 'VIR'],
            ['name' => 'EgyptAir', 'iata' => 'MS', 'icao' => 'MSR'],
            ['name' => 'Royal Jordanian', 'iata' => 'RJ', 'icao' => 'RJA'],
            ['name' => 'Saudia', 'iata' => 'SV', 'icao' => 'SVA'],
            ['name' => 'Gulf Air', 'iata' => 'GF', 'icao' => 'GFA'],
            ['name' => 'El Al Israel Airlines', 'iata' => 'LY', 'icao' => 'ELY'],
            ['name' => 'SriLankan Airlines', 'iata' => 'UL', 'icao' => 'ALK'],
            ['name' => 'Pakistan International Airlines', 'iata' => 'PK', 'icao' => 'PIA'],
            ['name' => 'Nepal Airlines', 'iata' => 'RA', 'icao' => 'RNA'],
            ['name' => 'Bangladesh Biman', 'iata' => 'BG', 'icao' => 'BBC'],
            ['name' => 'Bhutan Airlines', 'iata' => 'B3', 'icao' => 'BTN'],
            ['name' => 'Druk Air', 'iata' => 'KB', 'icao' => 'DRK'],
            ['name' => 'Tajik Air', 'iata' => '7J', 'icao' => 'TJK'],
            ['name' => 'Turkmenistan Airlines', 'iata' => 'T5', 'icao' => 'TUA'],
            ['name' => 'Uzbekistan Airways', 'iata' => 'HY', 'icao' => 'UZB'],
            ['name' => 'Air Koryo', 'iata' => 'JS', 'icao' => 'KOR'],
            ['name' => 'MIAT Mongolian Airlines', 'iata' => 'OM', 'icao' => 'MGL'],
            ['name' => 'China Southern Airlines', 'iata' => 'CZ', 'icao' => 'CSN'],
            ['name' => 'China Eastern Airlines', 'iata' => 'MU', 'icao' => 'CES'],
            ['name' => 'Air China', 'iata' => 'CA', 'icao' => 'CCA'],
            ['name' => 'Hainan Airlines', 'iata' => 'HU', 'icao' => 'CHH'],
            ['name' => 'Xiamen Airlines', 'iata' => 'MF', 'icao' => 'CXA'],
            ['name' => 'Shenzhen Airlines', 'iata' => 'ZH', 'icao' => 'CSZ'],
            ['name' => 'Sichuan Airlines', 'iata' => '3U', 'icao' => 'CSC'],
            ['name' => 'Tibet Airlines', 'iata' => 'TV', 'icao' => 'TBA'],
            ['name' => 'Beijing Capital Airlines', 'iata' => 'JD', 'icao' => 'CBJ'],
            ['name' => 'Kunming Airlines', 'iata' => 'KY', 'icao' => 'KNA'],
            ['name' => 'Juneyao Airlines', 'iata' => 'HO', 'icao' => 'DKH'],
            ['name' => 'Shanghai Airlines', 'iata' => 'FM', 'icao' => 'CSH'],
            ['name' => 'Spring Airlines', 'iata' => '9C', 'icao' => 'CQH'],
            ['name' => 'Okay Airways', 'iata' => 'BK', 'icao' => 'OKA'],
            ['name' => 'Lucky Air', 'iata' => '8L', 'icao' => 'LKE'],
            ['name' => 'Hong Kong Airlines', 'iata' => 'HX', 'icao' => 'CRK'],
            ['name' => 'Cathay Pacific', 'iata' => 'CX', 'icao' => 'CPA'],
            ['name' => 'Cathay Dragon', 'iata' => 'KA', 'icao' => 'HDA'],
            ['name' => 'HK Express', 'iata' => 'UO', 'icao' => 'HKE'],
            ['name' => 'Air Macau', 'iata' => 'NX', 'icao' => 'AMU'],
            ['name' => 'China Airlines', 'iata' => 'CI', 'icao' => 'CAL'],
            ['name' => 'EVA Air', 'iata' => 'BR', 'icao' => 'EVA'],
            ['name' => 'Mandarin Airlines', 'iata' => 'AE', 'icao' => 'MDA'],
            ['name' => 'Uni Air', 'iata' => 'B7', 'icao' => 'UIA'],
            ['name' => 'Starlux Airlines', 'iata' => 'JX', 'icao' => 'SJX'],
            ['name' => 'Japan Airlines', 'iata' => 'JL', 'icao' => 'JAL'],
            ['name' => 'All Nippon Airways', 'iata' => 'NH', 'icao' => 'ANA'],
            ['name' => 'Skymark Airlines', 'iata' => 'BC', 'icao' => 'SKY'],
            ['name' => 'Peach Aviation', 'iata' => 'MM', 'icao' => 'APJ'],
            ['name' => 'Air Do', 'iata' => 'HD', 'icao' => 'ADO'],
            ['name' => 'Solaseed Air', 'iata' => '6J', 'icao' => 'SNJ'],
            ['name' => 'StarFlyer', 'iata' => '7G', 'icao' => 'SFJ'],
            ['name' => 'Korean Air', 'iata' => 'KE', 'icao' => 'KAL'],
            ['name' => 'Asiana Airlines', 'iata' => 'OZ', 'icao' => 'AAR'],
            ['name' => 'T\'way Air', 'iata' => 'TW', 'icao' => 'TWB'],
            ['name' => 'Jeju Air', 'iata' => '7C', 'icao' => 'JJA'],
            ['name' => 'Jin Air', 'iata' => 'LJ', 'icao' => 'JNA'],
            ['name' => 'Air Busan', 'iata' => 'BX', 'icao' => 'ABL'],
            ['name' => 'Eastar Jet', 'iata' => 'ZE', 'icao' => 'ESR'],
            ['name' => 'Bamboo Airways', 'iata' => 'QH', 'icao' => 'BAV'],
            ['name' => 'VietJet Air', 'iata' => 'VJ', 'icao' => 'VJC'],
            ['name' => 'Jetstar Pacific Airlines', 'iata' => 'BL', 'icao' => 'PIC'],
            ['name' => 'Pacific Airlines', 'iata' => 'BL', 'icao' => 'PIC'],
            ['name' => 'Scoot', 'iata' => 'TR', 'icao' => 'TGW'],
            ['name' => 'SilkAir', 'iata' => 'MI', 'icao' => 'SLK'],
            ['name' => 'Royal Brunei Airlines', 'iata' => 'BI', 'icao' => 'RBA'],
            ['name' => 'Malaysia Airlines', 'iata' => 'MH', 'icao' => 'MAS'],
            ['name' => 'AirAsia', 'iata' => 'AK', 'icao' => 'AXM'],
            ['name' => 'Thai AirAsia', 'iata' => 'FD', 'icao' => 'AIQ'],
            ['name' => 'AirAsia X', 'iata' => 'D7', 'icao' => 'XAX'],
            ['name' => 'Thai AirAsia X', 'iata' => 'XJ', 'icao' => 'TAX'],
            ['name' => 'IndiGo', 'iata' => '6E', 'icao' => 'IGO'],
            ['name' => 'SpiceJet', 'iata' => 'SG', 'icao' => 'SEJ'],
            ['name' => 'Vistara', 'iata' => 'UK', 'icao' => 'VTI'],
            ['name' => 'Air India Express', 'iata' => 'IX', 'icao' => 'AXB'],
            ['name' => 'GoAir', 'iata' => 'G8', 'icao' => 'GOW'],
            ['name' => 'AirAsia India', 'iata' => 'I5', 'icao' => 'IAD'],
            ['name' => 'SriLankan Airlines', 'iata' => 'UL', 'icao' => 'ALK'],
            ['name' => 'Nepal Airlines', 'iata' => 'RA', 'icao' => 'RNA'],
            ['name' => 'Bangladesh Biman', 'iata' => 'BG', 'icao' => 'BBC'],
            ['name' => 'Druk Air', 'iata' => 'KB', 'icao' => 'DRK'],
            ['name' => 'MIAT Mongolian Airlines', 'iata' => 'OM', 'icao' => 'MGL'],
            ['name' => 'China Southern Airlines', 'iata' => 'CZ', 'icao' => 'CSN'],
            ['name' => 'China Eastern Airlines', 'iata' => 'MU', 'icao' => 'CES'],
            ['name' => 'Air China', 'iata' => 'CA', 'icao' => 'CCA'],
            ['name' => 'Hainan Airlines', 'iata' => 'HU', 'icao' => 'CHH'],
            ['name' => 'Xiamen Airlines', 'iata' => 'MF', 'icao' => 'CXA'],
            ['name' => 'Shenzhen Airlines', 'iata' => 'ZH', 'icao' => 'CSZ'],
            ['name' => 'Sichuan Airlines', 'iata' => '3U', 'icao' => 'CSC'],
            ['name' => 'Tibet Airlines', 'iata' => 'TV', 'icao' => 'TBA'],
            ['name' => 'Beijing Capital Airlines', 'iata' => 'JD', 'icao' => 'CBJ'],
            ['name' => 'Kunming Airlines', 'iata' => 'KY', 'icao' => 'KNA'],
            ['name' => 'Juneyao Airlines', 'iata' => 'HO', 'icao' => 'DKH'],
            ['name' => 'Shanghai Airlines', 'iata' => 'FM', 'icao' => 'CSH'],
            ['name' => 'Spring Airlines', 'iata' => '9C', 'icao' => 'CQH'],
            ['name' => 'Okay Airways', 'iata' => 'BK', 'icao' => 'OKA'],
            ['name' => 'Lucky Air', 'iata' => '8L', 'icao' => 'LKE'],
            ['name' => 'Hong Kong Airlines', 'iata' => 'HX', 'icao' => 'CRK'],
            ['name' => 'Cathay Pacific', 'iata' => 'CX', 'icao' => 'CPA'],
            ['name' => 'Cathay Dragon', 'iata' => 'KA', 'icao' => 'HDA'],
            ['name' => 'HK Express', 'iata' => 'UO', 'icao' => 'HKE'],
            ['name' => 'Air Macau', 'iata' => 'NX', 'icao' => 'AMU'],
            ['name' => 'China Airlines', 'iata' => 'CI', 'icao' => 'CAL'],
            ['name' => 'EVA Air', 'iata' => 'BR', 'icao' => 'EVA'],
            ['name' => 'Mandarin Airlines', 'iata' => 'AE', 'icao' => 'MDA'],
            ['name' => 'Uni Air', 'iata' => 'B7', 'icao' => 'UIA'],
            ['name' => 'Starlux Airlines', 'iata' => 'JX', 'icao' => 'SJX'],
            ['name' => 'Japan Airlines', 'iata' => 'JL', 'icao' => 'JAL'],
            ['name' => 'All Nippon Airways', 'iata' => 'NH', 'icao' => 'ANA'],
            ['name' => 'Skymark Airlines', 'iata' => 'BC', 'icao' => 'SKY'],
            ['name' => 'Peach Aviation', 'iata' => 'MM', 'icao' => 'APJ'],
            ['name' => 'Air Do', 'iata' => 'HD', 'icao' => 'ADO'],
            ['name' => 'Solaseed Air', 'iata' => '6J', 'icao' => 'SNJ'],
            ['name' => 'StarFlyer', 'iata' => '7G', 'icao' => 'SFJ'],
            ['name' => 'Korean Air', 'iata' => 'KE', 'icao' => 'KAL'],
            ['name' => 'Asiana Airlines', 'iata' => 'OZ', 'icao' => 'AAR'],
            ['name' => 'T\'way Air', 'iata' => 'TW', 'icao' => 'TWB'],
            ['name' => 'Jeju Air', 'iata' => '7C', 'icao' => 'JJA'],
            ['name' => 'Jin Air', 'iata' => 'LJ', 'icao' => 'JNA'],
            ['name' => 'Air Busan', 'iata' => 'BX', 'icao' => 'ABL'],
            ['name' => 'Eastar Jet', 'iata' => 'ZE', 'icao' => 'ESR'],
            ['name' => 'Bamboo Airways', 'iata' => 'QH', 'icao' => 'BAV'],
            ['name' => 'VietJet Air', 'iata' => 'VJ', 'icao' => 'VJC'],
            ['name' => 'Jetstar Pacific Airlines', 'iata' => 'BL', 'icao' => 'PIC'],
            ['name' => 'Pacific Airlines', 'iata' => 'BL', 'icao' => 'PIC'],
            ['name' => 'Scoot', 'iata' => 'TR', 'icao' => 'TGW'],
            ['name' => 'SilkAir', 'iata' => 'MI', 'icao' => 'SLK'],
            ['name' => 'Royal Brunei Airlines', 'iata' => 'BI', 'icao' => 'RBA'],
            ['name' => 'Malaysia Airlines', 'iata' => 'MH', 'icao' => 'MAS'],
            ['name' => 'AirAsia', 'iata' => 'AK', 'icao' => 'AXM'],
            ['name' => 'Thai AirAsia', 'iata' => 'FD', 'icao' => 'AIQ'],
            ['name' => 'AirAsia X', 'iata' => 'D7', 'icao' => 'XAX'],
            ['name' => 'Thai AirAsia X', 'iata' => 'XJ', 'icao' => 'TAX'],
            ['name' => 'IndiGo', 'iata' => '6E', 'icao' => 'IGO'],
            ['name' => 'SpiceJet', 'iata' => 'SG', 'icao' => 'SEJ'],
            ['name' => 'Vistara', 'iata' => 'UK', 'icao' => 'VTI'],
            ['name' => 'Air India Express', 'iata' => 'IX', 'icao' => 'AXB'],
            ['name' => 'GoAir', 'iata' => 'G8', 'icao' => 'GOW'],
            ['name' => 'AirAsia India', 'iata' => 'I5', 'icao' => 'IAD'],
            ['name' => 'SriLankan Airlines', 'iata' => 'UL', 'icao' => 'ALK'],
            ['name' => 'Nepal Airlines', 'iata' => 'RA', 'icao' => 'RNA'],
            ['name' => 'Bangladesh Biman', 'iata' => 'BG', 'icao' => 'BBC'],
            ['name' => 'Druk Air', 'iata' => 'KB', 'icao' => 'DRK'],
            ['name' => 'MIAT Mongolian Airlines', 'iata' => 'OM', 'icao' => 'MGL'],
            ['name' => 'China Southern Airlines', 'iata' => 'CZ', 'icao' => 'CSN'],
            ['name' => 'China Eastern Airlines', 'iata' => 'MU', 'icao' => 'CES'],
            ['name' => 'Air China', 'iata' => 'CA', 'icao' => 'CCA'],
            ['name' => 'Hainan Airlines', 'iata' => 'HU', 'icao' => 'CHH'],
            ['name' => 'Xiamen Airlines', 'iata' => 'MF', 'icao' => 'CXA'],
            ['name' => 'Shenzhen Airlines', 'iata' => 'ZH', 'icao' => 'CSZ'],
            ['name' => 'Sichuan Airlines', 'iata' => '3U', 'icao' => 'CSC'],
            ['name' => 'Tibet Airlines', 'iata' => 'TV', 'icao' => 'TBA'],
            ['name' => 'Beijing Capital Airlines', 'iata' => 'JD', 'icao' => 'CBJ'],
            ['name' => 'Kunming Airlines', 'iata' => 'KY', 'icao' => 'KNA'],
            ['name' => 'Juneyao Airlines', 'iata' => 'HO', 'icao' => 'DKH'],
            ['name' => 'Shanghai Airlines', 'iata' => 'FM', 'icao' => 'CSH'],
            ['name' => 'Spring Airlines', 'iata' => '9C', 'icao' => 'CQH'],
    ];

        DB::table('airlines')->insert($airlines);
    }
}
